context:
  name: bun
  version: 1.3.6

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - if: target_platform == "linux-64"
    then:
      url: https://github.com/oven-sh/${{ name }}/releases/download/${{ name }}-v${{ version }}/${{ name }}-linux-x64.zip
      sha256: 9ba98d2134550d6690875b23a4f5c48e74b7cb267e8cc1b8f52605921c6c11ef
  - if: target_platform == "linux-aarch64"
    then:
      url: https://github.com/oven-sh/${{ name }}/releases/download/${{ name }}-v${{ version }}/${{ name }}-linux-aarch64.zip
      sha256: 5afd12b366ba2d8297245cc29c039416334dd872152c1db02e5c8aa8c66e96b1
  - if: target_platform == "osx-64"
    then:
      url: https://github.com/oven-sh/${{ name }}/releases/download/${{ name }}-v${{ version }}/${{ name }}-darwin-x64.zip
      sha256: 83ef84c2a9d25dfef6ba0b31be3d8a09952ef311c71feca4488a628e96c26706
  - if: target_platform == "osx-arm64"
    then:
      url:  https://github.com/oven-sh/${{ name }}/releases/download/${{ name }}-v${{ version }}/${{ name }}-darwin-aarch64.zip
      sha256: 2af1ec8437759ab05b3b0ea421fe9e22e6c705cb4cb0751c326982642dace8fa

build:
  script:
    - wget https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/LICENSE.md
    - mkdir -p "${PREFIX}/bin"
    - mv bun "${PREFIX}/bin"

requirements:
  build:
    - wget

tests:
  - script:
      - bun --version

about:
  homepage: https://bun.com
  license: MIT
  license_file: LICENSE.md
  summary: A fast, incrementally adoptable all-in-one JavaScript, TypeScript & JSX toolkit
  description: |
    Bun is a fast, incrementally adoptable all-in-one JavaScript, TypeScript &
    JSX toolkit. Use individual tools like bun test or bun install in Node.js
    projects, or adopt the complete stack with a fast JavaScript runtime,
    bundler, test runner, and package manager built in. Bun aims for 100%
    Node.js compatibility.
  documentation: https://bun.com/docs
  repository: https://github.com/oven-sh/bun
