context:
  name: radare2
  version: 6.0.7
  sha256: 099af2b2ad97295c81f7ee6ed3ea8da961b5c66a08e1d2701722912f50d791cc

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/radareorg/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.xz
  sha256: ${{ sha256 }}

build:
  script: ./sys/install.sh --install

requirements:
  build:
    - ${{ compiler('c') }}
    - make

tests:
  - script:
      - r2 -h

about:
  homepage: https://radare.org
  license: Radare2
  license_file: COPYING.md
  summary: UNIX-like reverse engineering framework and command-line toolset
  description: |
    A free/libre toolchain for easing several low level tasks like forensics,
    software reverse engineering, exploiting, debugging, etc.
  documentation: https://book.rada.re
  repository: https://github.com/radareorg/radare2
