context:
  name: radare2
  version: 6.0.8
  checksum: f4cd10c80706e48309c8310ecf82dbb43128c1ccd236481904977845fec931d6

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/radareorg/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.xz
  sha256: ${{ checksum }}

build:
  script: ./sys/install.sh --install --prefix="${PREFIX}"

requirements:
  build:
    - ${{ compiler('c') }}
    - make

tests:
  - script:
      - r2 -h

about:
  homepage: https://radare.org
  license: LicenseRef-Radare2
  license_file: COPYING.md
  summary: UNIX-like reverse engineering framework and command-line toolset
  description: |
    radare2 is a free/libre toolchain for easing several low level tasks like
    forensics, software reverse engineering, exploiting, debugging, etc. It is
    composed by a bunch of libraries (which are extended with plugins) and
    programs that can be automated with almost any programming language.
  documentation: https://book.rada.re
  repository: https://github.com/radareorg/radare2
