context:
  name: ni
  version: 28.0.0
  sha256: c42870d682f7192d822f1f59660a1296ea1184e0bb0e107e44e6c564df90c458

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@antfu/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tgz

build:
  script:
    - npm install -g ${{ name }}-${{ version }}.tgz --prefix ${{ PREFIX }}
    - tar -xvf ${{ name }}-${{ version }}.tgz && cp -R package/ .

requirements:
  build:
    - nodejs
    - tar
  run:
    - nodejs

tests:
  - script:
      - ni -h

about:
  homepage: https://github.com/antfu-collective/ni
  license: MIT
  license_file: LICENSE
  summary: ni - use the right package manager
  description: ni detects your active package manager and uses the right one.
  documentation: https://github.com/antfu-collective/ni
  repository: https://github.com/antfu-collective/ni
