context:
  name: clib
  version: 2.8.7
  checksum: 83d5767e363c3ed4b4271000b9ce63b6e11b6c4740df910e0074f844fb34258e

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/clibs/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ checksum }}

build:
  script:
    - make install PREFIX="${PREFIX}"

requirements:
  build:
    - ${{ compiler('c') }}
  run:
    - libcurl

tests:
  - script:
      - clib --version

about:
  homepage: https://github.com/clibs/clib
  license: MIT
  license_file: LICENSE
  summary: A package manager for the C programming language
  description: |
    Clib is the Package manager for the C programming language. Basically is a
    suite of small C libraries that you can manually copy/paste into your
    projects, aimed at providing small, focused, discoverable
    "micro-libraries".
  documentation: https://github.com/clibs/clib
  repository: https://github.com/clibs/clib
