context:
  name: mole
  version: 1.25.0
  checksum: df22d7f2670b5331dc6c5d3ecef4c34adb7e3d3b925a36501df755835388cda4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tw93/Mole/archive/refs/tags/V${{ version }}.tar.gz
  sha256: ${{ checksum }}

build:
  script:
    - make build
    - mkdir "${PREFIX}/bin"
    - mv ./mo  ./mole ./bin/ ./lib/ "${PREFIX}/bin"

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - make

tests:
  - script:
      - mo -h

about:
  homepage: https://github.com/tw93/Mole
  license: MIT
  license_file: LICENSE
  summary: Deep clean and optimize your Mac
  description: mole deep cleans and optimizes your Mac.
  documentation: https://github.com/tw93/Mole
  repository: https://github.com/tw93/Mole
