context:
  name: mole
  version: 1.20.0
  sha256: 5c171ae3024d552d3f7e2c08148f6c7dc1a342bab89b81483e8a6d47d5d58b6a

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tw93/Mole/archive/refs/tags/V${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  script: 
    - make build
    - mkdir "${PREFIX}/bin"
    - mv ./mo  ./mole ./bin/ ./lib/ "${PREFIX}/bin"

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - make

tests:
  - script:
      - mo -h

about:
  homepage: https://github.com/tw93/Mole
  license: MIT
  license_file: LICENSE
  summary: Deep clean and optimize your Mac
  description: mole deep cleans and optimizes your Mac.
  documentation: https://github.com/tw93/Mole
  repository: https://github.com/tw93/Mole
